Tips at startup
meerk40t/meerk40t pull request #2282
Opened 2023-11-22 17:58 UTC by jpirnay

Display tips at startup (can be suppressed, will still be accessible via the Panes-Help menu)

<img width="269" alt="image" src="https://github.com/meerk40t/meerk40t/assets/2670784/16bd8b76-7375-4175-ba34-4cc05831ca92">

The tips can be maintained outside of the regular release cycle by updating a file on github: https://github.com/meerk40t/meerk40t/blob/main/locale/tips.txt
The logic will once a week query that file and hold a local copy. It will look first in the langauge-specific subdirectory and the fallback to the english version.
```
# This file contains tips to be displayed at program start. Every entry has up to 3 lines:
#   tip=xxxx Tip to be displayed
#   version=x.x.x (optional) Minimum version to apply, you can just omit that line to allow it for any version
#   cmd=xxxx Command to execute for the 'Try it out' button
# NB: Every tip= will reset cmd and version, so please use the sequence tip, cmd, version
#
# Example:
# tip=Did you know, these tips can be maintained and extended online.\nWow, that's great.
# cmd=
# version=0.9.3
#
# tip=That won't be visible for a while
# version=1.0
```

2023-11-23 05:05 UTC, tatarize requested changes
I don't love the idea of the program phoning home like that.

If we have tips we should hard code them at build time.

2023-11-23 17:17 UTC, jpirnay reviewed
Changes done according to agreement for intentional download

2023-11-23 22:09 UTC, tatarize commented on meerk40t/gui/tips.py
> +                            with urllib.request.urlopen(path) as file:
Could still download things without strict authorization.

2023-11-23 22:27 UTC, tatarize requested changes
If you deleted the images it could still download replacement images without explicit permission.

2023-11-24 10:32 UTC, jpirnay commented on meerk40t/gui/tips.py
> +                            with urllib.request.urlopen(path) as file:
resolved

2023-11-24 21:26 UTC, tatarize requested changes
I feel like this is really close. But, I can't easily revoke the ability to download those automatically. They should either have to press `update` to get the missing images or they should have to hit `update` on that individual image.

Once permissions are given here to automatically download the image it can't be revoked. Even just a text box that says `Image not found. Try updating.` would meet the otherwise seemingly stringent rules. Since it could just download the images after the user requested this.

* The program should not contact the internet without express permission.
* Permission should be revocable, but strongly preferred user initiated.

2023-11-24 21:33 UTC, tatarize commented
Even a checkbox that defaults to off, that gives a blanket `automatically update` would probably suffice. Just ask before you download, and let people suspend that access. Rather than begging them to click update a lot. Just `request access` and `allow revoke access`.

2023-11-24 22:42 UTC, tatarize approved these changes

2023-11-24 22:45 UTC, merged