Effects Toolbar Button and Default Effects Settings
meerk40t/meerk40t pull request #2506
Opened 2024-06-13 19:04 UTC by jondale

[Screencast from 2024-06-13 14-56-31.webm](https://github.com/meerk40t/meerk40t/assets/1604942/7824cd57-bc27-465f-ab07-e0e76492c6d3)

This PR makes two effective changes.

It changes the hatch button on the toolbar to an Effects Button that is populated by registered effects (currently wobble and hatch).

Additionally, it adds the ability to set default values for these effects that are device specific by adding a new Effects tab to each device config dialog.

One current weirdness that is perhaps added by this pr is that the preview in the hatch properties dialog is strange until you manually change it.  It might be an issue in conversion from str to Angle in that preview.  The hatch applies correctly to the object(s).

2024-06-17 15:35 UTC, jpirnay requested changes
invalid variable name, will crash

2024-06-17 15:35 UTC, jpirnay commented on meerk40t/core/elements/shapes.py
> +        elif distance is None:
Wrong variable name will crash

2024-06-25 14:09 UTC, jondale commented on meerk40t/core/elements/shapes.py
> +        elif distance is None:
updated.

2024-06-25 14:53 UTC, jpirnay approved these changes

2024-06-25 14:53 UTC, merged