User defined color
meerk40t/meerk40t pull request #976
Opened 2022-04-10 10:40 UTC by jpirnay

2022-04-11 06:56 UTC, tatarize requested changes
There should probably be a command to make things change instantly, rather than delaying until startup.

2022-04-11 06:58 UTC, tatarize commented
The issue is using set changes the value, but it doesn't change the derived values which are ultimately what causes the color.

0.7.x is mostly going to be abandoned going forward so hacking a solution in there is fine, but it might be best if it's easier to use and takes affect more directly.

2022-04-11 09:05 UTC, jpirnay commented
@tatarize 
It should be nearly immediate:
![color1](https://user-images.githubusercontent.com/2670784/162702385-ae6cdb23-5068-4174-891d-8858d737706d.gif)
The grid requires a redraw (i.e. a drag)
![color2](https://user-images.githubusercontent.com/2670784/162702413-e6f4cc15-74a5-48ed-80c7-d5fa65585d16.gif)
Is there a signal to listen to a "set ..."? Then I could force such a redraw...

2022-04-12 03:34 UTC, tatarize commented
See #979.

Part of the issue here is that you're automatically resetting the pens and brushes during the draw cycle. While it might not matter with the given graphics interface it's usually a bad idea for most of these things. Generally the way the drawing cycles work it's almost always best to already have the pens in place and the right color and then update that color.

This is why I thought it wouldn't automatically update with set because I figured it would be done like that, but it wasn't. I wrote the PR there with 0.8.x adaptations in mind. Saving colors as valid colors in the settings makes the most sense even then you could do `set color_grid green` though you'd need to restart the program to get that to take effect if you didn't switch the data with the `scene color` command.

2022-04-12 08:56 UTC, jpirnay commented
<img width="351" alt="image" src="https://user-images.githubusercontent.com/2670784/162922047-147d171a-d006-41ec-865e-0b3de4ab0f1a.png">
Incorporated tatarizes improvements and extended the color-theming for handles

2022-04-12 10:12 UTC, merged